import type { CBPLDefinitions } from './schemas.js';

/**
 * Generate markdown documentation from CBPL definitions
 */
export function generateMarkdown(definitions: CBPLDefinitions): string {
  let md = `# CBPL - Chunkback Prompt Language

> ⚠️  **AUTO-GENERATED DOCUMENTATION**
>
> This file is automatically generated from \`cbpl.definitions.json\`.
> Do not edit manually. Run \`pnpm codegen\` to regenerate.

CBPL (Chunkback Prompt Language) is a SQL-like command language for controlling LLM response generation with custom streaming and tool calling behavior.

## Commands

CBPL supports the following commands:

`;

  // Generate command documentation
  for (const [cmdName, cmd] of Object.entries(definitions.commands)) {
    md += `### ${cmdName}\n\n`;
    md += `${cmd.description}\n\n`;

    // Parameters
    if (cmd.parameters.length > 0) {
      md += `**Parameters:**\n\n`;
      for (const param of cmd.parameters) {
        md += `- \`${param.name}\` (${param.type}): ${param.description}`;
        if (param.validation) {
          const constraints = [];
          if (param.validation.min !== undefined) {
            constraints.push(`min: ${param.validation.min}`);
          }
          if (param.validation.max !== undefined) {
            constraints.push(`max: ${param.validation.max}`);
          }
          if (constraints.length > 0) {
            md += ` [${constraints.join(', ')}]`;
          }
        }
        md += `\n`;
      }
      md += `\n`;
    }

    // Syntax
    md += `**Syntax:**\n\n\`\`\`\n${cmdName}`;
    for (const param of cmd.parameters) {
      md += ` <${param.name}>`;
    }
    md += `\n\`\`\`\n\n`;

    // Examples
    if (cmd.examples.length > 0) {
      md += `**Examples:**\n\n`;
      for (const example of cmd.examples) {
        md += `\`\`\`cbpl\n${example}\n\`\`\`\n\n`;
      }
    }
  }

  // Additional documentation
  md += `## String Literals

Strings must be enclosed in double quotes. Escape sequences are supported:

\`\`\`cbpl
SAY "Hello \\"World\\""        # Escaped quotes
SAY "Line 1\\nLine 2"         # Newline
SAY "Tab\\there"              # Tab
SAY "Backslash: \\\\"          # Backslash
\`\`\`

## Multi-Statement Programs

CBPL supports multiple statements separated by newlines:

\`\`\`cbpl
SAY "First message"
CHUNKSIZE 3
CHUNKLATENCY 50
SAY "Second message with custom chunking"
TOOLCALL "get_weather" "New York"
\`\`\`

## Configuration Scope

\`CHUNKSIZE\` and \`CHUNKLATENCY\` statements affect all subsequent \`SAY\` statements until changed:

\`\`\`cbpl
SAY "Fast with default chunking"

CHUNKSIZE 5
SAY "Now 5 chars per chunk"

CHUNKLATENCY 100
SAY "5 chars per chunk, 100ms delay"

CHUNKSIZE 10
SAY "10 chars per chunk, still 100ms delay"
\`\`\`

`;

  return md;
}
